name: Generate Snake Game Contribution Grid

on:
  schedule:
    - cron: "0 */12 * * *"  # Executa a cada 12 horas
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar Snake Game
        uses: Platane/snk@v3
        with:
          github_user_name: Raphagamer03
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit e enviar a animação
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Atualizando Snake Game"
          branch: output
          file_pattern: "dist/*"
